// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_q_RGgifCZMywJIOxrJ94B4mRV0ZePCg',
    appId: '1:84793856079:web:0553af8d0b458121131a3a',
    messagingSenderId: '84793856079',
    projectId: 'skillora-app-1',
    authDomain: 'skillora-app-1.firebaseapp.com',
    storageBucket: 'skillora-app-1.firebasestorage.app',
    measurementId: 'G-3MK0CK1J06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Fo1tkyqNCdHn6arcp9o4JJfx7b-aqdU',
    appId: '1:84793856079:android:e16f8bd396ddef32131a3a',
    messagingSenderId: '84793856079',
    projectId: 'skillora-app-1',
    storageBucket: 'skillora-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwGW--FErqxnOR2qAkY03KH95N9qU-8Uo',
    appId: '1:84793856079:ios:379916f8ccbecb11131a3a',
    messagingSenderId: '84793856079',
    projectId: 'skillora-app-1',
    storageBucket: 'skillora-app-1.firebasestorage.app',
    iosBundleId: 'com.example.skillora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwGW--FErqxnOR2qAkY03KH95N9qU-8Uo',
    appId: '1:84793856079:ios:379916f8ccbecb11131a3a',
    messagingSenderId: '84793856079',
    projectId: 'skillora-app-1',
    storageBucket: 'skillora-app-1.firebasestorage.app',
    iosBundleId: 'com.example.skillora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_q_RGgifCZMywJIOxrJ94B4mRV0ZePCg',
    appId: '1:84793856079:web:27ed9cfcc62802c3131a3a',
    messagingSenderId: '84793856079',
    projectId: 'skillora-app-1',
    authDomain: 'skillora-app-1.firebaseapp.com',
    storageBucket: 'skillora-app-1.firebasestorage.app',
    measurementId: 'G-20FPTZGT69',
  );
}
